### ISSUE TITLE
Zinit is now ZI

### ISSUE THREAD

**Issue by AvinashReddy3108** [AvinashReddy3108/LitMux#11]
Docs: https://wiki.zshell.dev/

Need to migrate configs, prepare for breaking changes.

**Comment by prono69** [comment]
Wen update sir

**Comment by AvinashReddy3108** [comment]
I guess I won't need to. The community fork of zinit is more up-to-date than ZI itself, will stick to it.
https://github.com/zdharma-continuum/zinit
