### ISSUE TITLE
Bad for loop variable

### ISSUE THREAD

**Issue by rzlamrr** [AvinashReddy3108/LitMux#2]
I got this error:
`sh: 17: Syntax error: Bad for loop variable`

No any info i can give

**Comment by AvinashReddy3108** [comment]
> I got this error:
> `sh: 17: Syntax error: Bad for loop variable`
> 
> No any info i can give

I have updated the README.md file with the new instructions.
(The function which prints things in the center of the screen needs `bash`, not `sh` as used before to work so...)
