### ISSUE TITLE
How to disable extra buttons?

### ISSUE THREAD

**Issue by premjit1998** [AvinashReddy3108/LitMux#4]
![Screenshot_20210128-113620](https://user-images.githubusercontent.com/72644801/106097278-0f364600-615d-11eb-9f46-a40256ddc6f0.png)

**Comment by AvinashReddy3108** [comment]
Have a look at this Termux Wiki page: https://wiki.termux.com/wiki/Touch_Keyboard
Also, that's a nice looking keyboard you got there...

Where can I get that?

**Comment by premjit1998** [comment]
Yeap solved the problem.
