### ISSUE TITLE
No command zinit found, did you mean:                    Command kinit in package krb5

### ISSUE THREAD

**Issue by pokurt** [AvinashReddy3108/LitMux#6]
seems like they removed zinit. need to find a workaround for newer termux installations.

Package: com.termux
Version: 0.117
Source F-droid

**Comment by AvinashReddy3108** [comment]
Strange, Termux repos never had zinit in the first place... it's installed via another one liner..

**Comment by AvinashReddy3108** [comment]
@pokurt feel free to re-open this issue if this commit does not fix it.
