### ISSUE TITLE
No command zinit found, did you mean:  Command kinit in package krb5

### ISSUE THREAD

**Issue by starry69** [AvinashReddy3108/LitMux#8]
Getting this error everytime i open termux;
```
No command zinit found, did you mean:
 Command kinit in package krb5
```
Looks like current zinit installer script isn't working well anymore.

**Comment by AvinashReddy3108** [comment]
Updated the zinit's install script location, feel free to re-open this if not fixed.

**Comment by starry69** [comment]
Works fine now, thanks!
